services:
  csafety_oa_feishu:
    env_file:
      - .env.prod
    image: csafety-oa-feishu:latest
    container_name: csafety_oa_feishu_service # 改个名，以区分任务执行
    # network_mode: "host" # 考虑是否真的需要 host 模式
    environment:
      - TZ=Asia/Shanghai
    volumes: # 添加 volumes 来持久化 data 和 logs
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped